name: pre-commit

on: push

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: eifinger/setup-rye@v4
        id: setup-rye
      - name: Pin python-version from .python-version
        run: rye pin "$(cat .python-version)"
      - name: Setup Rye
        run: rye sync
      - name: Run pre-commit hooks
        run: rye run pre-commit run --all-files
